spin_manifest_version = 2

[application]
authors = ["jlcanela <jlcanelam@gmail.com>"]
description = ""
name = "saas-pattern-app"
version = "0.1.0"

[[trigger.http]]
route = "/api/..."
component = "backend"

[component.backend]
source = "apps/backend/target/backend.wasm"
exclude_files = ["**/node_modules"]

[component.backend.build]
command = "turbo build --filter=backend"
watch = ["apps/backend/src/**/*.ts", "apps/backend/package.json"]

[[trigger.http]]
route = "/..."
component = "frontend"

[component.frontend]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.2.1/spin_static_fs.wasm", digest = "sha256:5f05b15f0f7cd353d390bc5ebffec7fe25c6a6d7a05b9366c86dcb1a346e9f0f" }
files = [{ source = "apps/ui/dist", destination = "/" }]
environment = { FALLBACK_PATH = "index.html" }

[component.frontend.build]
command = "turbo build --filter=ui"
watch = ["apps/ui/src/**/*.{ts,tsx,css,json}", "apps/ui/package.json"]
