name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions: {} # Reset default permissions

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Only read permission for build job

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1  # Shallow clone for better performance

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      # Add security scanning
      - name: Security audit
        run: pnpm audit

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Cache Turbo
        uses: actions/cache@v4
        with:
          path: |
            .turbo
            node_modules/.cache/turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Build
        run: pnpm run build
        env:
          NODE_ENV: production
